# Generated by Django 3.2.16 on 2022-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectscreening',
            name='slug',
            field=models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
    ]
