# Generated by Django 3.1.14 on 2022-11-23 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectscreening',
            name='subject_identifier_aka',
            field=models.CharField(editable=False, help_text='track a previously allocated identifier.', max_length=50, null=True, verbose_name='Subject Identifier a.k.a'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='subject_identifier_as_pk',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='subject_identifier',
            field=models.CharField(max_length=50, verbose_name='Subject Identifier'),
        ),
    ]
