# Generated by Django 3.2.16 on 2022-10-23 14:16

from django.db import migrations, models
import edc_base.model_validators.eligibility


class Migration(migrations.Migration):

    dependencies = [
        ('study_subject', '0002_subjectscreening_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscreening',
            name='is_minor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'YES', participant may not be consented.", max_length=10, validators=[edc_base.model_validators.eligibility.eligible_if_no], verbose_name='Is a minor( Under 18 )'),
        ),
    ]
