# Generated by Django 4.1.2 on 2022-10-25 21:06

from django.db import migrations, models
import django.db.models.manager
import django_crypto_fields.fields.identity_field
import edc_base.sites.managers


class Migration(migrations.Migration):

    dependencies = [
        ('study_subject', '0004_appointment_subjectvisit_subjectconsent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityengagement',
            options={'verbose_name': 'Community Engagement Questionnaire', 'verbose_name_plural': 'Community Engagement Questionnaire'},
        ),
        migrations.AlterModelOptions(
            name='historicalsubjectconsent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Subject Consent', 'verbose_name_plural': 'historical Subject Consent'},
        ),
        migrations.AlterModelOptions(
            name='subjectconsent',
            options={'verbose_name': 'Subject Consent', 'verbose_name_plural': 'Subject Consent'},
        ),
        migrations.AlterModelManagers(
            name='subjectconsent',
            managers=[
                ('consent', django.db.models.manager.Manager()),
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='confirm_identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(help_text='Retype the identity number (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(default=None, help_text=' (Encryption: RSA local)', max_length=71, verbose_name='Identity number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='identity_type',
            field=models.CharField(choices=[('country_id', 'Country ID number'), ('drivers', "Driver's license"), ('passport', 'Passport'), ('hospital_no', 'Hospital number'), ('country_id_rcpt', 'Country ID receipt'), ('OTHER', 'Other')], default=None, max_length=25, verbose_name='What type of identity number is this?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='confirm_identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(help_text='Retype the identity number (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(default=None, help_text=' (Encryption: RSA local)', max_length=71, verbose_name='Identity number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='identity_type',
            field=models.CharField(choices=[('country_id', 'Country ID number'), ('drivers', "Driver's license"), ('passport', 'Passport'), ('hospital_no', 'Hospital number'), ('country_id_rcpt', 'Country ID receipt'), ('OTHER', 'Other')], default=None, max_length=25, verbose_name='What type of identity number is this?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='housemate',
            field=models.CharField(choices=[('Alone', 'Alone'), ('Partner/Spouse', 'Partner/Spouse'), ('Sibling', 'Sibling'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Who do you live with?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='housemate',
            field=models.CharField(choices=[('Alone', 'Alone'), ('Partner/Spouse', 'Partner/Spouse'), ('Sibling', 'Sibling'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Who do you live with?'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
    ]
