# Generated by Django 4.1.2 on 2022-10-25 21:20

import django.core.validators
from django.db import migrations, models
import django_crypto_fields.fields.encrypted_char_field
import django_crypto_fields.fields.firstname_field
import django_crypto_fields.fields.lastname_field
import edc_consent.validators
import edc_model_fields.fields.date_estimated


class Migration(migrations.Migration):

    dependencies = [
        ('study_subject', '0005_alter_communityengagement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='first_name',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='guardian_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if participant is a minor.<BR>Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Guardian's last and first name"),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='initials',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, validators=[django.core.validators.RegexValidator(message='Ensure initials consist of letters only in upper case, no spaces.', regex='^[A-Z]{2,3}$')]),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='is_dob_estimated',
            field=edc_model_fields.fields.date_estimated.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='last_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='subject_type',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='first_name',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='guardian_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if participant is a minor.<BR>Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Guardian's last and first name"),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='initials',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, validators=[django.core.validators.RegexValidator(message='Ensure initials consist of letters only in upper case, no spaces.', regex='^[A-Z]{2,3}$')]),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='is_dob_estimated',
            field=edc_model_fields.fields.date_estimated.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='last_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='subject_type',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
