# Generated by Django 4.1.2 on 2022-10-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_subject', '0006_historicalsubjectconsent_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='subject_identifier',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
