# Generated by Django 3.2.16 on 2022-11-04 07:16

from django.db import migrations, models
import edc_base.model_fields.date_estimated


class Migration(migrations.Migration):

    dependencies = [
        ('study_subject', '0007_alter_historicalsubjectconsent_subject_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='subject_identifier',
            field=models.CharField(max_length=50, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='subject_identifier',
            field=models.CharField(max_length=50, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='identity_type',
            field=models.CharField(max_length=25, verbose_name='What type of identity number is this?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='is_dob_estimated',
            field=edc_base.model_fields.date_estimated.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='subject_identifier',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='subject_identifier',
            field=models.CharField(max_length=50, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='identity_type',
            field=models.CharField(max_length=25, verbose_name='What type of identity number is this?'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='is_dob_estimated',
            field=edc_base.model_fields.date_estimated.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='subject_identifier',
            field=models.CharField(max_length=50, verbose_name='Subject Identifier'),
        ),
    ]
